{% set name = "psygnal" %}
{% set version = "0.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f64f62dee2306fc1c22050a59b6c6cdad126e04b0cf50e393ff858a1da719096

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  script_env:
    - HATCH_BUILD_HOOKS_ENABLE=1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
  host:
    - pip
    - python
    - hatchling >=1.8.0
    - hatch-vcs
    - hatch-mypyc >=0.13.0
    - mypy >=2.1.0
    - mypyc >=2.1.0
    - mypy_extensions >=0.4.2
    #- pydantic >2.10.0
    #- attrs
    #- msgspec
    #- wrapt
  run:
    - python
    #- pydantic >2.10.0
    # - wrapt  # provides 'proxy' extra

test:
  imports:
    - psygnal
    - psygnal.containers
    - psygnal.utils
  requires:
    - pip
    - python
  commands:
    - pip check
    - python -c "import psygnal; print(psygnal._compiled); assert psygnal._compiled"

about:
  home: https://github.com/tlambert03/psygnal
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Pure python implementation of Qt Signals
  doc_url: https://psygnal.readthedocs.io/en/latest/
  dev_url: https://github.com/tlambert03/psygnal

extra:
  recipe-maintainers:
    - tlambert03
